name: Create Contact Form Issue
on:
  repository_dispatch:
    types: [contact-form-submission]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
          script: |
            const { name, email, message } = context.payload.client_payload;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Contact Form: ${name}`,
              body: `From: ${name}
Email: ${email}

Message:
${message}`,
              labels: ['contact-form']
            });